CREATE TABLE USUARIO ( 
	USUARIOID NUMBER PRIMARY KEY, 
	NOMEUSUARIO VARCHAR2(80) NOT NULL, 
	ENDERECO VARCHAR2(100) NOT NULL
); 
 
CREATE SEQUENCE Usuario_ID_SEQ;  
 
CREATE OR REPLACE TRIGGER TR_SEQ_Usuario BEFORE INSERT ON Usuario FOR EACH ROW  
BEGIN 
	SELECT USUARIO_ID_SEQ.NEXTVAL INTO :new.USUARIOID FROM dual; 
END; 
 
--DROP TRIGGER TR_SEQ_USUARIO; 
--DROP SEQUENCE USUARIO_ID_SEQ; 
--DROP TABLE USUARIO;